// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/AfterSchoolAdventurePlanner-x29eFp/App.tsx": () => import("../components/mockups/templates/AfterSchoolAdventurePlanner-x29eFp/App.tsx")
};
